### ISSUE TITLE
Outdated text in Alectryon quickstart

### ISSUE THREAD

**Issue by shardulc** [mit-plv/blog#1]
On https://github.com/mit-plv/blog/blob/master/content/2020-11-09_alectryon.rst#authoring-tips:

> (Hi, reader! Are you thinking “why isn't this on MELPA?” Great question! It's because I haven't had the time to do it yet. But you can — [yes](https://github.com/melpa/melpa/blob/master/README.md), you! In exchange, I promise I'll sing your praises every time your name comes up in conversation — I might even refer to you as ‘writer-of-MELPA-recipes extraordinaire’.
>
> Alternatively, if you're a member of this most distinguished category of people who write more grant proposals than Emacs Lisp programs, you should drop me a line: I'm on the academic job market this year, so we should chat!)

Both those paragraphs are out of date now, I think :)

**Comment by shardulc** [comment]
@cpitclaudel

**Comment by cpitclaudel** [comment]
That's the nature of blog posts, they're frozen in time.  I'm not too bothered by that ^^
